### ISSUE TITLE
Screen glitches

### ISSUE THREAD

**Issue by reypg87** [benlau/quickandroid#2]
When I run the tests/quickandroidexample occurs some screen glitches(black and white flashes) just before showing the main app content, when the entire application is hided again happen that.

**Comment by benlau** [comment]
Hi,

With the latest version with Qt 5.4 , the problem should be fixed. Please check.

**Comment by toby20130333** [comment]
this is a good project for qter to dev android app by qt
thanks

**Comment by ofuochi** [comment]
HI Benlau. You done a great job but I have some serious issues with the library and this is because am totally new to this. Whenever I try to preview any of the components in the designer window, I don't see anything! Am sorry if this is a stupid complain but am addicted to you library already and I really need to use it on a project but I can't preview the components. I just see a very tiny red or blue dot. I'm a beginner with QML and that's why I depend heavily on the designer mode. Please is there something am doing wrong? Here for example is the ActionBar.qml in the design mode
![capture1](https://cloud.githubusercontent.com/assets/13614165/10558734/00e00d2e-74d3-11e5-842e-362915a217a3.PNG) Please respond!
